version: 2.1
jobs:
  native-aliases-arm64:
    resource_class: arm.medium
    machine:
      image: ubuntu-2404:current
    environment:
      CFLAGS: -Wextra -Werror -march=armv8.2-a+simd+crypto+crc+bf16 -DSIMDE_ENABLE_NATIVE_ALIASES -DSIMDE_NATIVE_ALIASES_TESTING
      CXXFLAGS: -Wextra -Werror -march=armv8.2-a+simd+crypto+crc+bf16 -DSIMDE_ENABLE_NATIVE_ALIASES -DSIMDE_NATIVE_ALIASES_TESTING
      CC: gcc
      CXX: g++
    steps:
      - run: sudo apt-get update && sudo apt-get install -y git ninja-build pipx gcc-14 g++-14 libxml2-utils ccache
      - checkout
      - restore_cache:
         keys:
            - ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}
            - ccache-{{ .Environment.CIRCLE_JOB }}-master
            - ccache-{{ .Environment.CIRCLE_JOB }}
      - run: cat /proc/cpuinfo /proc/meminfo
      - run:
          command: |
            ccache --set-config=max_size='500M'
            ccache --set-config=compression=true
            ccache -p
            ccache -z
      - run: pipx install meson==0.55.1
      - run: ./test/native-aliases.sh
      - run: |
          export PATH=/usr/lib/ccache:${PATH}
          CC="ccache gcc-14" CXX="ccache g++-14" ${HOME}/.local/bin/meson setup build -Db_coverage=true
          ninja -C build -v -j $(nproc)
      - run: /usr/bin/ccache -s
      - save_cache:
          key: 'ccache-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ epoch }}'
          paths: [ "/home/circleci/.cache/ccache" ]
          when: always
      - run: ninja -C build -v test



workflows:
  version: 2
  test:
    jobs:
      - native-aliases-arm64:
          filters:
            branches:
              ignore:
              - /^ci/(?!circleci).*$/
