name: CI

on:
  push:
    branches-ignore:
      - 'ci/**'
      - '!ci/gha**'
      - 'dependabot/**'
  pull_request:
    branches:
      - 'master'

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clang-qemu:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
        - version: 21
          cross: s390x
          arch_gnu: s390x
          arch_deb: s390x
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: CPU Information
      run: cat /proc/cpuinfo
    - name: Install nightly llvm
      if: ${{ matrix.cross == 's390x' }}
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 21
    - name: Install APT Dependencies
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa && \
        sudo apt-get update -y && \
        sudo apt-get -y --no-install-recommends install ninja-build \
          binfmt-support clang-${{ matrix.version }} \
          qemu-user-static pipx libc6-${{ matrix.arch_deb }}-cross libstdc++-14-dev-${{ matrix.arch_deb }}-cross \
          binutils-${{ matrix.arch_gnu }}-linux-gnu${{ matrix.arch_gnu_abi }}
        pipx install meson==0.55.1
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ matrix.version }}${{ matrix.extra }}-${{ matrix.cross }}
        evict-old-files: job
        verbose: 2
    - name: add ccache to the build path
      run: |
        export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
    - name: Configure
      run: |
        meson setup --cross-file=docker/cross-files/${{ matrix.cross }}-clang-${{ matrix.version }}${{ matrix.extra }}-ccache.cross build \
          || (cat build/meson-logs/meson-log.txt ; false)
    - name: Build
      run: ninja -C build -v
    - name: Test
      run: |
        # shellcheck disable=SC2046
        meson test -C build --print-errorlogs --print-errorlogs $(meson test -C build --list | grep -v emul)
